backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: public
public_folder: /img

collections:
  - name: "dogs" # Used in routes, e.g., /admin/collections/blog
    label: "dog" # Used in the UI
    format: "frontmatter"
    folder: "content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Name", name: "name", widget: "string" }
